### ISSUE TITLE
idea克隆下来报错

### ISSUE THREAD

**Issue by rainbowsky911** [ProYI/RESTfulDemo#1]
![idea](https://user-images.githubusercontent.com/16053250/49715882-cf662900-fc8c-11e8-81ac-4ba6cca01ed8.png)

是缺少jar了吗，楼主，

**Comment by ProYI** [comment]
不好意思哈，不太会玩github，一直没注意才看到。你问题解决了吗？数据源可能因为dataSource这个名称的原因，我自己没有啥问题。我在其他地方遇到过这种问题，在dao层的dataSource命名变成XXXXDataSource，可以更好的找到数据源
